### PR TITLE
Check Memory/FS availability on healthcheck

### PR DESCRIPTION
**Pull request by xDarksome**
# Description

Checks that memory usage is below 75% and that a temp file can be created.

## How Has This Been Tested?

Manually

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Comment by nopestack** [comment]
@xDarksome is this PR still relevant?

**Comment by xDarksome** [comment]
Yes, @arein wanted this for all services a year ago. But the idea never got implemented anywhere else to my knowledge
Still, may be useful

**Review by arein — APPROVED** [review]
🙏

**Comment by xav** [comment]
@arein Hey! Can you please remove me from the reviewers / close the PR? It shows up in my "reviews requested" list and there's nothing I can do about it. Thanks.

**Pull request closed without merging**
